language: node_js
node_js:
  - 10
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
deploy:
  provider: npm
  email: guy@cornelius.io
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
